# Generated by Django 5.1.4 on 2024-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avtar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
